package config

var (
	// LinkedinClientID ...
	LinkedinClientID = "81py8v1s43xg9n"
	// ServerURL ...
	ServerURL = "http://localhost:8888"
	// TestServerURL ...
	TestServerURL = "https://dca752fb.ngrok.io"
	// LinkedinScopes ...
	LinkedinScopes = []string{"r_liteprofile", "r_emailaddress", "w_member_social"}
)
